apiVersion: v1
kind: Service
metadata:
  name: platforms-clusterip-srv
spec:
  type: ClusterIp
  selector:
    app: platformsservice
  ports:
    - name: platformsservice
      protocol: TCP
      port: 80
      targetPort: 8080