apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbitmq-cluster
---
apiVersion: v1
kind: Service
metadata:
  name: loadbalancer-rabbitmq-cluster
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/component: rabbitmq
    app.kubernetes.io/name: rabbitmq-cluster
    app.kubernetes.io/part-of: rabbitmq
  ports:
    - protocol: TCP
      port: 15672
      targetPort: 15672